version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.13
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./gradlew test

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: my2.7.x
